name: Build App
 on:
    push:
      # Trigger only for main branch.
      branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

     jobs:
      build:
        runs-on: ubuntu-20.04
      # Steps definition starts here
      steps:
        # Get the app source
        - name: Get the source
          uses: actions/checkout@v2
